title: My Blog
description: Personal writing, photos, and notes
theme: jekyll-theme-cayman

url: "https://austingayler.github.io"
baseurl: "/blog"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
