backend:
  name: github
  repo: username/blog
  branch: main

media_folder: "assets/img"
public_folder: "/blog/assets/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "categories", widget: "list" }
